/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as LaptopsUsageRouteImport } from './routes/laptops.$usage'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media.$'
import { Route as AuthenticatedAdminResourceIndexRouteImport } from './routes/_authenticated/admin.$resource.index'
import { Route as AuthenticatedAdminResourceIdRouteImport } from './routes/_authenticated/admin.$resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsUsageRoute = LaptopsUsageRouteImport.update({
  id: '/laptops/$usage',
  path: '/laptops/$usage',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminResourceIndexRoute =
  AuthenticatedAdminResourceIndexRouteImport.update({
    id: '/admin/$resource/',
    path: '/admin/$resource/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResourceIdRoute =
  AuthenticatedAdminResourceIdRouteImport.update({
    id: '/admin/$resource/$id',
    path: '/admin/$resource/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/laptops/$usage': typeof LaptopsUsageRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$id': typeof AuthenticatedAdminResourceIdRoute
  '/admin/$resource/': typeof AuthenticatedAdminResourceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/laptops/$usage': typeof LaptopsUsageRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$id': typeof AuthenticatedAdminResourceIdRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/laptops/$usage': typeof LaptopsUsageRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$resource/$id': typeof AuthenticatedAdminResourceIdRoute
  '/_authenticated/admin/$resource/': typeof AuthenticatedAdminResourceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bulk-orders'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/brands/$slug'
    | '/collections/$slug'
    | '/laptops/$usage'
    | '/policies/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/collections/'
    | '/products/'
    | '/services/'
    | '/admin/logs'
    | '/admin/settings'
    | '/api/media/$'
    | '/admin/'
    | '/admin/$resource/$id'
    | '/admin/$resource/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bulk-orders'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/brands/$slug'
    | '/collections/$slug'
    | '/laptops/$usage'
    | '/policies/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/blog'
    | '/collections'
    | '/products'
    | '/services'
    | '/admin/logs'
    | '/admin/settings'
    | '/api/media/$'
    | '/admin'
    | '/admin/$resource/$id'
    | '/admin/$resource'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bulk-orders'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/brands/$slug'
    | '/collections/$slug'
    | '/laptops/$usage'
    | '/policies/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/collections/'
    | '/products/'
    | '/services/'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/settings'
    | '/api/media/$'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$resource/$id'
    | '/_authenticated/admin/$resource/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  LaptopsUsageRoute: typeof LaptopsUsageRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/$usage': {
      id: '/laptops/$usage'
      path: '/laptops/$usage'
      fullPath: '/laptops/$usage'
      preLoaderRoute: typeof LaptopsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/$resource/': {
      id: '/_authenticated/admin/$resource/'
      path: '/admin/$resource'
      fullPath: '/admin/$resource/'
      preLoaderRoute: typeof AuthenticatedAdminResourceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$resource/$id': {
      id: '/_authenticated/admin/$resource/$id'
      path: '/admin/$resource/$id'
      fullPath: '/admin/$resource/$id'
      preLoaderRoute: typeof AuthenticatedAdminResourceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminResourceIdRoute: typeof AuthenticatedAdminResourceIdRoute
  AuthenticatedAdminResourceIndexRoute: typeof AuthenticatedAdminResourceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminResourceIdRoute: AuthenticatedAdminResourceIdRoute,
  AuthenticatedAdminResourceIndexRoute: AuthenticatedAdminResourceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  LaptopsUsageRoute: LaptopsUsageRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
