INSERT INTO public.settings (key, value, group_name, label) VALUES
('section_hero_enabled','true','Homepage Sections','Show hero slider section'),
('hero_slider_interval_ms','5200','Homepage Sections','Hero slide interval (ms)'),
('section_showcase_enabled','true','Homepage Sections','Show category showcase section'),
('showcase_eyebrow','Shop by category','Homepage Sections','Showcase eyebrow'),
('showcase_title','Hardware for every requirement','Homepage Sections','Showcase heading'),
('featured_eyebrow','Current stock','Homepage Sections','Featured products eyebrow'),
('featured_title','Featured refurbished systems','Homepage Sections','Featured products heading'),
('section_testimonials_enabled','true','Homepage Sections','Show testimonials section'),
('testimonials_eyebrow','Customer feedback','Homepage Sections','Testimonials eyebrow'),
('testimonials_title','What buyers say','Homepage Sections','Testimonials heading'),
('section_facility_enabled','true','Homepage Sections','Show facility photo strip'),
('facility_eyebrow','Inside our facility','Homepage Sections','Facility strip eyebrow'),
('facility_title','Stock, testing benches and dispatch','Homepage Sections','Facility strip heading'),
('facility_marquee_speed_s','28','Homepage Sections','Facility strip scroll speed (seconds)'),
('section_cta_enabled','true','Homepage Sections','Show bottom call-to-action section'),
('cta_title','Need a bulk quote or a specific configuration?','Homepage Sections','CTA heading'),
('cta_text','Send us your requirement and we will come back with availability, configuration options and pricing.','Homepage Sections','CTA text'),
('cta_button1_text','Request a quote','Homepage Sections','CTA button 1 text'),
('cta_button1_link','/bulk-orders','Homepage Sections','CTA button 1 link'),
('cta_button2_text','Contact us','Homepage Sections','CTA button 2 text'),
('cta_button2_link','/contact','Homepage Sections','CTA button 2 link'),
('animations_enabled','true','Animation','Enable website animations'),
('animation_duration_ms','700','Animation','Animation duration (ms)'),
('animation_stagger_ms','80','Animation','Stagger delay between items (ms)'),
('animation_kenburns_enabled','true','Animation','Slow zoom effect on hero images')
ON CONFLICT (key) DO NOTHING;