INSERT INTO public.brands (name, slug, sort_order)
SELECT 'Intel', 'intel', 11
WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE slug = 'intel');

INSERT INTO public.categories (name, slug, short_description, description, icon, sort_order)
SELECT 'Processors', 'processors',
  'Intel desktop processors in bulk lots, tested and verified.',
  'Bulk stock of pre-owned Intel Core i3, i5, i7 and Pentium desktop processors across generations. All units are 100% tested and verified. Wholesale rates, minimum order 100 pieces, negotiable for one-shot buyers.',
  'Cpu', 9
WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE slug = 'processors');

INSERT INTO public.products (
  sku, name, slug, brand_id, category_id, product_type, condition, grade,
  processor_brand, processor_model, processor_generation,
  price, show_price, stock_quantity, availability,
  short_description, description,
  is_featured, is_new_arrival, is_active,
  seo_title, seo_description
) VALUES
('RCS-CPU-I3-10G','Intel Core i3 10th Gen Processor','intel-core-i3-10th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','10th Gen',
 6500,true,1,'In Stock (Bulk)',
 'Intel Core i3 10th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i3 10th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 6,500 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i3 10th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i3 10th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-9G','Intel Core i3 9th Gen Processor','intel-core-i3-9th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','9th Gen',
 1600,true,2,'In Stock (Bulk)',
 'Intel Core i3 9th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i3 9th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 1,600 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i3 9th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i3 9th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-8G','Intel Core i3 8th Gen Processor','intel-core-i3-8th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','8th Gen',
 1500,true,31,'In Stock (Bulk)',
 'Intel Core i3 8th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i3 8th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 1,500 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 true,true,true,
 'Intel Core i3 8th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i3 8th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-7G','Intel Core i3 7th Gen Processor','intel-core-i3-7th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','7th Gen',
 375,true,810,'In Stock (Bulk)',
 'Intel Core i3 7th Gen desktop processor. Bulk wholesale lot of 810 pieces.',
 'Pre-owned Intel Core i3 7th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 375 per piece. Large lot of 810 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 true,true,true,
 'Intel Core i3 7th Gen Processor Bulk Wholesale (810 pcs) | R Computer Solutions',
 'Bulk lot of 810 tested Intel Core i3 7th Gen processors at Rs 375 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-6G','Intel Core i3 6th Gen Processor','intel-core-i3-6th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','6th Gen',
 350,true,410,'In Stock (Bulk)',
 'Intel Core i3 6th Gen desktop processor. Bulk wholesale lot of 410 pieces.',
 'Pre-owned Intel Core i3 6th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 350 per piece. Large lot of 410 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 true,true,true,
 'Intel Core i3 6th Gen Processor Bulk Wholesale (410 pcs) | R Computer Solutions',
 'Bulk lot of 410 tested Intel Core i3 6th Gen processors at Rs 350 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-4G','Intel Core i3 4th Gen Processor','intel-core-i3-4th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','4th Gen',
 350,true,128,'In Stock (Bulk)',
 'Intel Core i3 4th Gen desktop processor. Bulk wholesale lot of 128 pieces.',
 'Pre-owned Intel Core i3 4th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 350 per piece. Lot of 128 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i3 4th Gen Processor Bulk Wholesale (128 pcs) | R Computer Solutions',
 'Bulk lot of 128 tested Intel Core i3 4th Gen processors at Rs 350 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-3G','Intel Core i3 3rd Gen Processor','intel-core-i3-3rd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','3rd Gen',
 350,true,42,'In Stock (Bulk)',
 'Intel Core i3 3rd Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i3 3rd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 350 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i3 3rd Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i3 3rd Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I3-2G','Intel Core i3 2nd Gen Processor','intel-core-i3-2nd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i3','2nd Gen',
 250,true,32,'In Stock (Bulk)',
 'Intel Core i3 2nd Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i3 2nd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 250 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i3 2nd Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i3 2nd Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-PENT-46G','Intel Pentium 4th/6th Gen Processor','intel-pentium-4th-6th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Pentium','4th/6th Gen',
 150,true,500,'In Stock (Bulk)',
 'Intel Pentium 4th/6th Gen desktop processor. Bulk wholesale lot of 500 pieces.',
 'Pre-owned Intel Pentium 4th/6th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 150 per piece. Large lot of 500 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Pentium Processor Bulk Wholesale (500 pcs) | R Computer Solutions',
 'Bulk lot of 500 tested Intel Pentium processors at Rs 150 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-11G','Intel Core i5 11th Gen Processor','intel-core-i5-11th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','11th Gen',
 11000,true,1,'In Stock (Bulk)',
 'Intel Core i5 11th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 11th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 11,000 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 11th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 11th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-10G','Intel Core i5 10th Gen Processor','intel-core-i5-10th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','10th Gen',
 10500,true,2,'In Stock (Bulk)',
 'Intel Core i5 10th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 10th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 10,500 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 10th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 10th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-8G','Intel Core i5 8th Gen Processor','intel-core-i5-8th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','8th Gen',
 4200,true,40,'In Stock (Bulk)',
 'Intel Core i5 8th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 8th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 4,200 per piece. Lot of 40 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 8th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 8th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-7G','Intel Core i5 7th Gen Processor','intel-core-i5-7th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','7th Gen',
 1800,true,42,'In Stock (Bulk)',
 'Intel Core i5 7th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 7th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 1,800 per piece. Lot of 42 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 7th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 7th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-6G','Intel Core i5 6th Gen Processor','intel-core-i5-6th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','6th Gen',
 1500,true,224,'In Stock (Bulk)',
 'Intel Core i5 6th Gen desktop processor. Bulk wholesale lot of 224 pieces.',
 'Pre-owned Intel Core i5 6th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 1,500 per piece. Large lot of 224 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 true,true,true,
 'Intel Core i5 6th Gen Processor Bulk Wholesale (224 pcs) | R Computer Solutions',
 'Bulk lot of 224 tested Intel Core i5 6th Gen processors at Rs 1,500 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-4G','Intel Core i5 4th Gen Processor','intel-core-i5-4th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','4th Gen',
 1650,true,30,'In Stock (Bulk)',
 'Intel Core i5 4th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 4th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 1,650 per piece. Lot of 30 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 4th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 4th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-3G','Intel Core i5 3rd Gen Processor','intel-core-i5-3rd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','3rd Gen',
 950,true,102,'In Stock (Bulk)',
 'Intel Core i5 3rd Gen desktop processor. Bulk wholesale lot of 102 pieces.',
 'Pre-owned Intel Core i5 3rd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 950 per piece. Lot of 102 pieces available - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 3rd Gen Processor Bulk Wholesale (102 pcs) | R Computer Solutions',
 'Bulk lot of 102 tested Intel Core i5 3rd Gen processors at Rs 950 per piece. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I5-2G','Intel Core i5 2nd Gen Processor','intel-core-i5-2nd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i5','2nd Gen',
 750,true,17,'In Stock (Bulk)',
 'Intel Core i5 2nd Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i5 2nd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 750 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i5 2nd Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i5 2nd Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-8G','Intel Core i7 8th Gen Processor','intel-core-i7-8th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','8th Gen',
 7900,true,9,'In Stock (Bulk)',
 'Intel Core i7 8th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 8th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 7,900 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 8th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 8th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-7G','Intel Core i7 7th Gen Processor','intel-core-i7-7th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','7th Gen',
 4500,true,10,'In Stock (Bulk)',
 'Intel Core i7 7th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 7th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 4,500 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 7th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 7th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-6G','Intel Core i7 6th Gen Processor','intel-core-i7-6th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','6th Gen',
 3750,true,19,'In Stock (Bulk)',
 'Intel Core i7 6th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 6th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 3,750 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 6th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 6th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-4G','Intel Core i7 4th Gen Processor','intel-core-i7-4th-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','4th Gen',
 3400,true,1,'In Stock (Bulk)',
 'Intel Core i7 4th Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 4th Generation desktop processor, 100% tested and verified. Wholesale rate Rs 3,400 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 4th Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 4th Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-3G','Intel Core i7 3rd Gen Processor','intel-core-i7-3rd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','3rd Gen',
 2800,true,16,'In Stock (Bulk)',
 'Intel Core i7 3rd Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 3rd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 2,800 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 3rd Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 3rd Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.'),
('RCS-CPU-I7-2G','Intel Core i7 2nd Gen Processor','intel-core-i7-2nd-gen-processor',
 (SELECT id FROM public.brands WHERE slug='intel'),(SELECT id FROM public.categories WHERE slug='processors'),
 'Processor','Pre-Owned','Tested','Intel','Core i7','2nd Gen',
 2500,true,1,'In Stock (Bulk)',
 'Intel Core i7 2nd Gen desktop processor. Bulk wholesale lot.',
 'Pre-owned Intel Core i7 2nd Generation desktop processor, 100% tested and verified. Wholesale rate Rs 2,500 per piece. Part of a bulk lot - minimum order 100 pieces across the processor range. Rates negotiable for one-shot buyers.',
 false,true,true,
 'Intel Core i7 2nd Gen Processor Bulk Wholesale | R Computer Solutions',
 'Bulk lot of tested Intel Core i7 2nd Gen processors at wholesale rates. Minimum 100 pcs. Navi Mumbai. Call 8691914641.');