import type { ResourceConfig } from "./resources";

const seo = [
  { name: "seo_title", label: "SEO title", type: "text" as const, group: "SEO" },
  { name: "seo_description", label: "SEO description", type: "textarea" as const, group: "SEO" },
  { name: "seo_keywords", label: "SEO keywords", type: "text" as const, group: "SEO" },
];

export const extraResources: Record<string, ResourceConfig> = {
  collections: {
    key: "collections",
    table: "collections",
    label: "Collections",
    singular: "Collection",
    description: "Best sellers, hot deals, budget ranges and any custom product grouping.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["name", "slug"],
    slugFrom: "name",
    columns: [
      { name: "name", label: "Name" },
      { name: "slug", label: "Slug" },
      { name: "kind", label: "Type", type: "badge" },
      { name: "sort_order", label: "Order" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, group: "Basics" },
      { name: "slug", label: "URL slug", type: "text", required: true, group: "Basics" },
      {
        name: "kind",
        label: "Type",
        type: "select",
        options: ["manual", "auto", "budget"],
        group: "Basics",
        help: "manual = you pick products, auto = rule based, budget = price limit.",
      },
      { name: "short_description", label: "Short description", type: "textarea", group: "Basics" },
      { name: "description", label: "Description", type: "richtext", group: "Basics" },
      { name: "image_url", label: "Image", type: "image", group: "Media" },
      { name: "banner_url", label: "Banner", type: "image", group: "Media" },
      { name: "is_featured", label: "Featured on home page", type: "boolean", group: "Visibility" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Visibility" },
      { name: "is_active", label: "Active", type: "boolean", group: "Visibility" },
      ...seo,
    ],
  },

  usage_tags: {
    key: "usage_tags",
    table: "usage_tags",
    label: "Shop by usage",
    singular: "Usage tag",
    description: "For students, for office, for programming and other use-case landing pages.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["name", "slug"],
    slugFrom: "name",
    columns: [
      { name: "name", label: "Name" },
      { name: "slug", label: "Slug" },
      { name: "sort_order", label: "Order" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, group: "Basics" },
      { name: "slug", label: "URL slug", type: "text", required: true, group: "Basics" },
      { name: "icon", label: "Icon name", type: "text", group: "Basics" },
      { name: "short_description", label: "Short description", type: "textarea", group: "Basics" },
      { name: "description", label: "Description", type: "richtext", group: "Basics" },
      { name: "image_url", label: "Image", type: "image", group: "Media" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Visibility" },
      { name: "is_active", label: "Active", type: "boolean", group: "Visibility" },
      { name: "seo_title", label: "SEO title", type: "text", group: "SEO" },
      { name: "seo_description", label: "SEO description", type: "textarea", group: "SEO" },
    ],
  },

  banners: {
    key: "banners",
    table: "banners",
    label: "Banners",
    singular: "Banner",
    description: "Hero and promotional banners with scheduling.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["title", "placement"],
    columns: [
      { name: "image_url", label: "", type: "image" },
      { name: "title", label: "Title" },
      { name: "placement", label: "Placement", type: "badge" },
      { name: "sort_order", label: "Order" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "eyebrow", label: "Eyebrow text", type: "text", group: "Content" },
      { name: "title", label: "Heading", type: "text", group: "Content" },
      { name: "subtitle", label: "Subheading", type: "textarea", group: "Content" },
      { name: "cta_text", label: "Button text", type: "text", group: "Content" },
      { name: "cta_link", label: "Button link", type: "text", group: "Content" },
      { name: "secondary_cta_text", label: "Secondary button text", type: "text", group: "Content" },
      { name: "secondary_cta_link", label: "Secondary button link", type: "text", group: "Content" },
      { name: "image_url", label: "Image", type: "image", group: "Media" },
      { name: "mobile_image_url", label: "Mobile image", type: "image", group: "Media" },
      { name: "alt_text", label: "Alt text", type: "text", group: "Media" },
      {
        name: "placement",
        label: "Placement",
        type: "select",
        options: ["hero", "home-strip", "products", "business"],
        group: "Scheduling",
      },
      { name: "starts_at", label: "Starts", type: "date", group: "Scheduling" },
      { name: "ends_at", label: "Ends", type: "date", group: "Scheduling" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Scheduling" },
      { name: "is_active", label: "Active", type: "boolean", group: "Scheduling" },
    ],
  },

  blog: {
    key: "blog",
    table: "blog_posts",
    label: "Blog posts",
    singular: "Blog post",
    description: "Buying guides and articles. Publish only content you stand behind.",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["title", "slug", "excerpt"],
    slugFrom: "title",
    columns: [
      { name: "cover_image_url", label: "", type: "image" },
      { name: "title", label: "Title" },
      { name: "author_name", label: "Author" },
      { name: "is_published", label: "Published", type: "boolean" },
      { name: "published_at", label: "Published on", type: "date" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, group: "Basics" },
      { name: "slug", label: "URL slug", type: "text", required: true, group: "Basics" },
      { name: "excerpt", label: "Excerpt", type: "textarea", group: "Basics" },
      { name: "body", label: "Article", type: "richtext", group: "Basics" },
      { name: "author_name", label: "Author", type: "text", group: "Basics" },
      { name: "reading_minutes", label: "Reading time (minutes)", type: "number", group: "Basics" },
      { name: "tags", label: "Tags", type: "tags", group: "Basics", help: "One per line." },
      { name: "cover_image_url", label: "Cover image", type: "image", group: "Media" },
      { name: "cover_image_alt", label: "Cover image alt text", type: "text", group: "Media" },
      { name: "is_featured", label: "Featured", type: "boolean", group: "Visibility" },
      { name: "is_published", label: "Published", type: "boolean", group: "Visibility" },
      { name: "published_at", label: "Publish date", type: "date", group: "Visibility" },
      ...seo,
      { name: "canonical_url", label: "Canonical URL", type: "text", group: "SEO" },
      { name: "og_image", label: "Social image", type: "image", group: "SEO" },
      { name: "robots", label: "Robots", type: "text", group: "SEO" },
    ],
  },

  blog_categories: {
    key: "blog_categories",
    table: "blog_categories",
    label: "Blog categories",
    singular: "Blog category",
    description: "Groups for your articles.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["name", "slug"],
    slugFrom: "name",
    columns: [
      { name: "name", label: "Name" },
      { name: "slug", label: "Slug" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, group: "Basics" },
      { name: "slug", label: "URL slug", type: "text", required: true, group: "Basics" },
      { name: "description", label: "Description", type: "textarea", group: "Basics" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Visibility" },
      { name: "is_active", label: "Active", type: "boolean", group: "Visibility" },
    ],
  },

  attributes: {
    key: "attributes",
    table: "attributes",
    label: "Attributes",
    singular: "Attribute",
    description: "Filter attributes such as RAM, storage or processor family.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["name", "code"],
    columns: [
      { name: "name", label: "Name" },
      { name: "code", label: "Code" },
      { name: "is_filterable", label: "Filterable", type: "boolean" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, group: "Basics" },
      { name: "code", label: "Code", type: "text", required: true, group: "Basics" },
      {
        name: "input_type",
        label: "Input type",
        type: "select",
        options: ["select", "multiselect", "range", "text"],
        group: "Basics",
      },
      { name: "is_filterable", label: "Show as filter", type: "boolean", group: "Visibility" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Visibility" },
      { name: "is_active", label: "Active", type: "boolean", group: "Visibility" },
    ],
  },

  product_requests: {
    key: "product_requests",
    table: "product_requests",
    label: "Product requests",
    singular: "Product request",
    description: "Items customers asked for that you did not have in stock.",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["product_name", "name", "phone"],
    canCreate: false,
    statusOptions: ["New", "Sourcing", "Quoted", "Fulfilled", "Closed"],
    columns: [
      { name: "created_at", label: "Received", type: "date" },
      { name: "product_name", label: "Requested" },
      { name: "name", label: "Name" },
      { name: "phone", label: "Phone" },
      { name: "status", label: "Status", type: "badge" },
    ],
    fields: [
      { name: "product_name", label: "Requested product", type: "text", group: "Request" },
      { name: "quantity", label: "Quantity", type: "text", group: "Request" },
      { name: "budget", label: "Budget", type: "text", group: "Request" },
      { name: "message", label: "Message", type: "textarea", group: "Request" },
      { name: "name", label: "Name", type: "text", group: "Contact" },
      { name: "phone", label: "Phone", type: "text", group: "Contact" },
      { name: "email", label: "Email", type: "text", group: "Contact" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["New", "Sourcing", "Quoted", "Fulfilled", "Closed"],
        group: "Follow up",
      },
      { name: "admin_notes", label: "Internal notes", type: "textarea", group: "Follow up" },
    ],
  },

  newsletter: {
    key: "newsletter",
    table: "newsletter_subscribers",
    label: "Newsletter",
    singular: "Subscriber",
    description: "People who asked for stock and offer updates.",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["email", "name"],
    canCreate: false,
    columns: [
      { name: "created_at", label: "Joined", type: "date" },
      { name: "email", label: "Email" },
      { name: "name", label: "Name" },
      { name: "source", label: "Source" },
      { name: "status", label: "Status", type: "badge" },
    ],
    fields: [
      { name: "email", label: "Email", type: "text", group: "Subscriber" },
      { name: "name", label: "Name", type: "text", group: "Subscriber" },
      { name: "source", label: "Source", type: "text", group: "Subscriber" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Subscribed", "Unsubscribed", "Bounced"],
        group: "Subscriber",
      },
    ],
  },

  redirects: {
    key: "redirects",
    table: "redirects",
    label: "Redirects",
    singular: "Redirect",
    description: "Send old website URLs to the matching new page so search rankings are kept.",
    orderBy: { column: "from_path", ascending: true },
    searchColumns: ["from_path", "to_path"],
    columns: [
      { name: "from_path", label: "From" },
      { name: "to_path", label: "To" },
      { name: "status_code", label: "Code" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "from_path", label: "Old path", type: "text", required: true, group: "Basics", placeholder: "/old-page" },
      { name: "to_path", label: "New path", type: "text", required: true, group: "Basics", placeholder: "/products" },
      { name: "status_code", label: "Status code", type: "number", group: "Basics", help: "301 permanent, 302 temporary." },
      { name: "note", label: "Note", type: "text", group: "Basics" },
      { name: "is_active", label: "Active", type: "boolean", group: "Basics" },
    ],
  },

  navigation: {
    key: "navigation",
    table: "navigation_items",
    label: "Navigation",
    singular: "Menu item",
    description: "Extra links in the header and footer menus.",
    orderBy: { column: "sort_order", ascending: true },
    searchColumns: ["label", "href"],
    columns: [
      { name: "menu", label: "Menu", type: "badge" },
      { name: "label", label: "Label" },
      { name: "href", label: "Link" },
      { name: "sort_order", label: "Order" },
      { name: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "menu", label: "Menu", type: "select", options: ["main", "footer", "utility"], group: "Basics" },
      { name: "label", label: "Label", type: "text", required: true, group: "Basics" },
      { name: "href", label: "Link", type: "text", required: true, group: "Basics" },
      { name: "icon", label: "Icon name", type: "text", group: "Basics" },
      { name: "sort_order", label: "Sort order", type: "number", group: "Basics" },
      { name: "is_active", label: "Active", type: "boolean", group: "Basics" },
    ],
  },
};
